// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomeDocumentDataSlicesSlice =
  | ModelSectionSlice
  | ClosingSlice
  | CalloutSlice
  | HomeInfoSlice
  | HeroHomeSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Nav → pages*
 */
export interface NavDocumentDataPagesItem {
  /**
   * name field in *Nav → pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.pages[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * href field in *Nav → pages*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.pages[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Content for Nav documents
 */
interface NavDocumentData {
  /**
   * pages field in *Nav*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.pages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pages: prismic.GroupField<Simplify<NavDocumentDataPagesItem>>;
}

/**
 * Nav document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

export type AllDocumentTypes = HomeDocument | NavDocument;

/**
 * Item in *Callout → Default → Primary → stats*
 */
export interface CalloutSliceDefaultPrimaryStatsItem {
  /**
   * text field in *Callout → Default → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Callout → alternate → Primary → stats*
 */
export interface CalloutSliceAlternatePrimaryStatsItem {
  /**
   * text field in *Callout → alternate → Primary → stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.stats[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Callout → Default → Primary*
 */
export interface CalloutSliceDefaultPrimary {
  /**
   * title field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Designed for Modern Living
   * - **API ID Path**: callout.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * stats field in *Callout → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<CalloutSliceDefaultPrimaryStatsItem>>;

  /**
   * note field in *Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.note
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  note: prismic.KeyTextField;

  /**
   * image field in *Callout → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalloutSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Callout → alternate → Primary*
 */
export interface CalloutSliceAlternatePrimary {
  /**
   * title field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * stats field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stats: prismic.GroupField<Simplify<CalloutSliceAlternatePrimaryStatsItem>>;

  /**
   * note field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.note
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  note: prismic.KeyTextField;

  /**
   * image field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * inner image field in *Callout → alternate → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: callout.alternate.primary.inner_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  inner_image: prismic.ImageField<never>;
}

/**
 * alternate variation for Callout Slice
 *
 * - **API ID**: `alternate`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSliceAlternate = prismic.SharedSliceVariation<
  "alternate",
  Simplify<CalloutSliceAlternatePrimary>,
  never
>;

/**
 * Slice variation for *Callout*
 */
type CalloutSliceVariation = CalloutSliceDefault | CalloutSliceAlternate;

/**
 * Callout Shared Slice
 *
 * - **API ID**: `callout`
 * - **Description**: Callout
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalloutSlice = prismic.SharedSlice<
  "callout",
  CalloutSliceVariation
>;

/**
 * Primary content in *Closing → Default → Primary*
 */
export interface ClosingSliceDefaultPrimary {
  /**
   * title field in *Closing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: closing.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * image field in *Closing → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: closing.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta title field in *Closing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: closing.default.primary.cta_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_title: prismic.KeyTextField;

  /**
   * cta text field in *Closing → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: closing.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;
}

/**
 * Default variation for Closing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClosingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ClosingSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Closing*
 */
type ClosingSliceVariation = ClosingSliceDefault;

/**
 * Closing Shared Slice
 *
 * - **API ID**: `closing`
 * - **Description**: Closing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ClosingSlice = prismic.SharedSlice<
  "closing",
  ClosingSliceVariation
>;

/**
 * Primary content in *HeroHome → Default → Primary*
 */
export interface HeroHomeSliceDefaultPrimary {
  /**
   * title field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hello Prismic
   * - **API ID Path**: hero_home.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * image field in *HeroHome → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_home.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroHomeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

/**
 * Item in *HomeInfo → Default → Primary → sections*
 */
export interface HomeInfoSliceDefaultPrimarySectionsItem {
  /**
   * img field in *HomeInfo → Default → Primary → sections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_info.default.primary.sections[].img
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  img: prismic.ImageField<never>;

  /**
   * text field in *HomeInfo → Default → Primary → sections*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Pure Minimalist Aesthetic – A sleek, refined silhouette that embodies sophistication.
   * - **API ID Path**: home_info.default.primary.sections[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *HomeInfo → Default → Primary*
 */
export interface HomeInfoSliceDefaultPrimary {
  /**
   * title field in *HomeInfo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Why Choose This Table?
   * - **API ID Path**: home_info.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * sections field in *HomeInfo → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home_info.default.primary.sections[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  sections: prismic.GroupField<
    Simplify<HomeInfoSliceDefaultPrimarySectionsItem>
  >;
}

/**
 * Default variation for HomeInfo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInfoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HomeInfoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeInfo*
 */
type HomeInfoSliceVariation = HomeInfoSliceDefault;

/**
 * HomeInfo Shared Slice
 *
 * - **API ID**: `home_info`
 * - **Description**: HomeInfo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HomeInfoSlice = prismic.SharedSlice<
  "home_info",
  HomeInfoSliceVariation
>;

/**
 * Primary content in *ModelSection → Default → Primary*
 */
export interface ModelSectionSliceDefaultPrimary {
  /**
   * model field in *ModelSection → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 1
   * - **API ID Path**: model_section.default.primary.model
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  model: prismic.SelectField<"1" | "2", "filled">;

  /**
   * title field in *ModelSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: model_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *ModelSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: model_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for ModelSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ModelSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ModelSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ModelSection*
 */
type ModelSectionSliceVariation = ModelSectionSliceDefault;

/**
 * ModelSection Shared Slice
 *
 * - **API ID**: `model_section`
 * - **Description**: ModelSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ModelSectionSlice = prismic.SharedSlice<
  "model_section",
  ModelSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataPagesItem,
      AllDocumentTypes,
      CalloutSlice,
      CalloutSliceDefaultPrimaryStatsItem,
      CalloutSliceDefaultPrimary,
      CalloutSliceAlternatePrimaryStatsItem,
      CalloutSliceAlternatePrimary,
      CalloutSliceVariation,
      CalloutSliceDefault,
      CalloutSliceAlternate,
      ClosingSlice,
      ClosingSliceDefaultPrimary,
      ClosingSliceVariation,
      ClosingSliceDefault,
      HeroHomeSlice,
      HeroHomeSliceDefaultPrimary,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
      HomeInfoSlice,
      HomeInfoSliceDefaultPrimarySectionsItem,
      HomeInfoSliceDefaultPrimary,
      HomeInfoSliceVariation,
      HomeInfoSliceDefault,
      ModelSectionSlice,
      ModelSectionSliceDefaultPrimary,
      ModelSectionSliceVariation,
      ModelSectionSliceDefault,
    };
  }
}
