// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  callout: dynamic(() => import("./Callout")),
  closing: dynamic(() => import("./Closing")),
  hero_home: dynamic(() => import("./HeroHome")),
  home_info: dynamic(() => import("./HomeInfo")),
};
